# Generated by Django 5.1.4 on 2024-12-08 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('what_makes_it_good', models.TextField(blank=True)),
                ('my_experience', models.TextField(blank=True)),
                ('main_features', models.TextField(blank=True)),
                ('my_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('best_for', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('affiliate_link', models.URLField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_discontinued', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedals.manufacturer')),
                ('pedal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedals.pedaltype')),
            ],
            options={
                'ordering': ['manufacturer__name', 'name'],
            },
        ),
    ]
