# Generated by Django 5.1.4 on 2024-12-08 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('years_of_experience', models.IntegerField()),
                ('profile_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pedal',
            name='affiliate_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedal',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedal',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedals', to='pedals.manufacturer'),
        ),
        migrations.AlterField(
            model_name='pedal',
            name='pedal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedals', to='pedals.pedaltype'),
        ),
        migrations.AddField(
            model_name='pedal',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedals', to='pedals.author'),
        ),
    ]
