# Generated by Django 5.1.4 on 2024-12-08 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0002_author_alter_pedal_affiliate_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='pedals.pedal')),
            ],
            options={
                'unique_together': {('pedal', 'ip_address')},
            },
        ),
    ]
