# Generated by Django 5.1.4 on 2024-12-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0004_add_review_to_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('pedal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pedals.pedal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
