# Generated by Django 5.1.4 on 2024-12-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0006_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160),
        ),
        migrations.AddField(
            model_name='pedal',
            name='what_makes_it_bad',
            field=models.TextField(blank=True, help_text='What makes this pedal bad?'),
        ),
        migrations.AlterField(
            model_name='pedal',
            name='what_makes_it_good',
            field=models.TextField(blank=True, help_text='What makes this pedal good?'),
        ),
    ]
