# Generated by Django 4.2.8 on 2024-12-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0008_author_updated_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='specifications',
            field=models.TextField(blank=True, help_text='Technical specifications like power requirements, dimensions, input/output jacks, etc.'),
        ),
    ]
