# Generated by Django 5.0 on 2024-12-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0009_pedal_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='heading_best_for',
            field=models.CharField(blank=True, default='Best For', max_length=100),
        ),
        migrations.AddField(
            model_name='pedal',
            name='heading_my_experience',
            field=models.CharField(blank=True, default='My Experience', max_length=100),
        ),
        migrations.AddField(
            model_name='pedal',
            name='heading_specifications',
            field=models.CharField(blank=True, default='Specifications', max_length=100),
        ),
        migrations.AddField(
            model_name='pedal',
            name='heading_what_makes_it_good',
            field=models.CharField(blank=True, default='What Makes It Good', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedal',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
